kind = "web"
previewPath = "/"
title = "Untuk Aida"
version = "1.0.0"
id = "artifacts/aida"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18826

[services.development]
run = "pnpm --filter @workspace/aida run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/aida", "run", "build" ]
publicDir = "artifacts/aida/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18826"
BASE_PATH = "/"
